{"level":"error","message":"Unhandled Rejection:","promise":{},"reason":"Maximum call stack size exceeded","stack":"RangeError: Maximum call stack size exceeded\n    at logger.error (file:///C:/Users/admin/Desktop/CWS_Caller_Project/utils/logger.js:147:16)\n    at logger.error (file:///C:/Users/admin/Desktop/CWS_Caller_Project/utils/logger.js:148:10)\n    at logger.error (file:///C:/Users/admin/Desktop/CWS_Caller_Project/utils/logger.js:148:10)\n    at logger.error (file:///C:/Users/admin/Desktop/CWS_Caller_Project/utils/logger.js:148:10)\n    at logger.error (file:///C:/Users/admin/Desktop/CWS_Caller_Project/utils/logger.js:148:10)\n    at logger.error (file:///C:/Users/admin/Desktop/CWS_Caller_Project/utils/logger.js:148:10)\n    at logger.error (file:///C:/Users/admin/Desktop/CWS_Caller_Project/utils/logger.js:148:10)\n    at logger.error (file:///C:/Users/admin/Desktop/CWS_Caller_Project/utils/logger.js:148:10)\n    at logger.error (file:///C:/Users/admin/Desktop/CWS_Caller_Project/utils/logger.js:148:10)\n    at logger.error (file:///C:/Users/admin/Desktop/CWS_Caller_Project/utils/logger.js:148:10)","timestamp":"2025-08-13T19:26:48.161Z"}
{"level":"error","message":"Unhandled Rejection:","promise":{},"reason":"Database connection failed","stack":"Error: Database connection failed\n    at AppError.databaseError (file:///C:/Users/admin/Desktop/CWS_Caller_Project/utils/AppError.js:53:19)\n    at User.initPool (file:///C:/Users/admin/Desktop/CWS_Caller_Project/models/BaseModel.js:36:22)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-08-13T19:27:34.491Z"}
{"level":"error","message":"Unhandled Rejection:","promise":{},"reason":"Database connection failed","stack":"Error: Database connection failed\n    at AppError.databaseError (file:///C:/Users/admin/Desktop/CWS_Caller_Project/utils/AppError.js:53:19)\n    at User.initPool (file:///C:/Users/admin/Desktop/CWS_Caller_Project/models/BaseModel.js:36:22)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-08-13T19:42:11.225Z"}
{"level":"error","message":"Unhandled Rejection:","promise":{},"reason":"Database connection failed","stack":"Error: Database connection failed\n    at AppError.databaseError (file:///C:/Users/admin/Desktop/CWS_Caller_Project/utils/AppError.js:53:19)\n    at User.initPool (file:///C:/Users/admin/Desktop/CWS_Caller_Project/models/BaseModel.js:36:22)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-08-13T20:04:10.489Z"}
